""" 
    #@Python Programs
    #@Name : query_constants.py
    #@Since : 23-01-2024
    #@Author : Srinithi K
    #@Version : 1.0
    #@See : This file contains for query"""

AUTHORIZED_USERS="""CREATE TABLE IF NOT EXISTS authorized_users(id  INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)PRIMARY KEY,roll_no VARCHAR(12),reg_no INT,name VARCHAR(50),section VARCHAR(5)), UNIQUE (reg_no)"""

USER_PROFILE="""CREATE TABLE IF NOT EXISTS user_profile(id  INT GENERATED BY DEFAULT AS IDENTITY(START WITH 5000)PRIMARY KEY,reg_no INT,email_id VARCHAR(50) NOT NULL,name VARCHAR(50),password VARCHAR(100),FOREIGN KEY (reg_no) references authorized_users(reg_no),UNIQUE(email_id))"""

NOMINEE_DETAILS ="""CREATE TABLE IF NOT EXISTS nominee_details(id  INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000)PRIMARY KEY,first_name varchar(50),middle_name VARCHAR(50),last_name VARCHAR(50),year_of_passing INT,contact_no BIGINT,email_id VARCHAR(100),contact_address VARCHAR, award_category  award_category,award_field_working award_field_working,organisation_name VARCHAR(100),designation VARCHAR(50),career_highlights VARCHAR,awards VARCHAR,social_welfare VARCHAR,ngo VARCHAR,membership VARCHAR,other_activities VARCHAR,webinar VARCHAR,alumni_talks VARCHAR,others VARCHAR,proof_link VARCHAR)"""

EVENT_REGISTER_DETAILS ="""CREATE TABLE IF NOT EXISTS event_register_details(id  INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000)PRIMARY KEY,first_name varchar(50),middle_name VARCHAR(50),last_name VARCHAR(50),year_of_passing INT,contact_no BIGINT,email_id VARCHAR(100),contact_address VARCHAR)"""


def insert_query_marker(table_name,info_dict):
    columns=", ".join(info_dict.keys())
    values=", ".join(info_dict.values())
    tuple_fields=(table_name,columns,values)
    INSERT_QUERY = "INSERT INTO %s (%s) VALUES (%s)" % tuple_fields
    return INSERT_QUERY

FETCH_AUTHORIZED_USERS = "select json_agg(items)::jsonb from (select * from authorized_users)items"

FETCH_LOGIN_USERS = "select json_agg(items)::jsonb from (select * from user_profile where reg_no=%s)items"

